/**
 * Realistic Mock and Fallback Data for Islamabad & Rawalpindi
 * Used when backend is offline or for instant client demonstration.
 */

export const DEMO_SCENARIOS = {
  urdu_violation: {
    id: "rep-demo-001",
    created_at: new Date().toISOString(),
    transcript_raw: "آلو مارکیٹ میں دو سو روپے کلو بیچ رہے ہیں جبکہ سرکاری لسٹ میں سو روپے ہے۔ غریب بندہ کہاں جائے؟",
    detected_language: "Urdu",
    category: "PERA - Overpricing",
    urgency: "High",
    status: "Pending",
    extraction_confidence: 0.98,
    needs_review: false,
    item_name: "Potato",
    item_canonical_id: "aloo",
    unit: "kg",
    reported_price: 200.0,
    official_price: 100.0,
    price_difference_pkr: 100.0,
    percentage_overcharge: 100.0,
    native_response: "آپ کی شکایت موصول ہو چکی ہے۔ سرکاری ریٹ 100 روپے کے مقابلے میں 200 روپے چارج کرنا سنگین خلاف ورزی ہے۔ پرائس کنٹرول مجسٹریٹ کو کارروائی کے لیے مطلع کر دیا گیا ہے۔",
    routing_agency: "PERA - Price Enforcement & Regulatory Authority",
    helpline_reference: "1717",
    location_area: "Raja Bazaar, Rawalpindi",
    shop_name: "Madina Cash & Carry",
    lat: 33.6028,
    lng: 73.0551,
    admin_notes: null,
  },
  english_normal: {
    id: "rep-demo-002",
    created_at: new Date().toISOString(),
    transcript_raw: "Purchased milk from fresh dairy stall in F-7 Markaz for 190 rupees per liter. Is that within the official cap?",
    detected_language: "English",
    category: "PERA - Price Verification",
    urgency: "Low",
    status: "Resolved",
    extraction_confidence: 0.95,
    needs_review: false,
    item_name: "Milk",
    item_canonical_id: "doodh",
    unit: "liter",
    reported_price: 190.0,
    official_price: 200.0,
    price_difference_pkr: -10.0,
    percentage_overcharge: -5.0,
    native_response: "Your rate check is complete. The reported price of Rs 190/liter is within the official notified rate of Rs 200/liter. No violation detected.",
    routing_agency: "ICT District Administration",
    helpline_reference: "051-9108194",
    location_area: "F-7 Markaz, Islamabad",
    shop_name: "Chaudhry Milk Shop",
    lat: 33.7205,
    lng: 73.0567,
    admin_notes: "Rate within legal limits. Verified.",
  },
  unknown_item: {
    id: "rep-demo-003",
    created_at: new Date().toISOString(),
    transcript_raw: "I paid 1200 rupees for imported breakfast cereal in Super Market. Are cereal prices regulated?",
    detected_language: "English",
    category: "Consumer Advisory",
    urgency: "Low",
    status: "Pending",
    extraction_confidence: 0.72,
    needs_review: true,
    item_name: "Imported Cereal",
    item_canonical_id: null,
    unit: "pack",
    reported_price: 1200.0,
    official_price: null,
    price_difference_pkr: null,
    percentage_overcharge: null,
    native_response: "Imported breakfast cereals are not currently on the essential commodity price notification list. Your inquiry has been forwarded to the consumer protection cell for review.",
    routing_agency: "Consumer Protection Court Islamabad",
    helpline_reference: "051-9108194",
    location_area: "F-6 Super Market, Islamabad",
    shop_name: "Al-Fateh Store",
    lat: 33.7294,
    lng: 73.0763,
    admin_notes: "Item not on Price Control Act schedule.",
  }
};

export const MOCK_ADMIN_COMPLAINTS = [
  {
    id: "comp-raw-001",
    created_at: "2026-10-09T18:40:00Z",
    transcript_raw: "راجہ بازار میں آلو 200 روپے کلو بیچ رہے ہیں جبکہ سرکاری لسٹ میں 100 روپے ہے۔",
    detected_language: "Urdu",
    category: "PERA - Overpricing",
    urgency: "High",
    status: "Investigating",
    extraction_confidence: 0.98,
    needs_review: false,
    item_name: "Potato",
    item_canonical_id: "aloo",
    unit: "kg",
    reported_price: 200.0,
    official_price: 100.0,
    price_difference_pkr: 100.0,
    percentage_overcharge: 100.0,
    native_response: "آپ کی شکایت موصول ہو چکی ہے۔ پرائس کنٹرول مجسٹریٹ کو کارروائی کے لیے مطلع کر دیا گیا ہے۔",
    routing_agency: "PERA - Price Enforcement",
    helpline_reference: "1717",
    location_area: "Raja Bazaar, Rawalpindi",
    shop_name: "Madina Cash & Carry",
    lat: 33.6028,
    lng: 73.0551,
    location_accuracy_m: 12,
    location_source: "GPS",
    admin_notes: "Team dispatched for inspection at 19:15."
  },
  {
    id: "comp-raw-002",
    created_at: "2026-10-09T17:15:00Z",
    transcript_raw: "پیاز 160 روپے کلو دے رہے ہیں صدر بازار میں، سرکاری ریٹ 120 روپے ہے۔",
    detected_language: "Urdu",
    category: "PERA - Overpricing",
    urgency: "Medium",
    status: "Pending",
    extraction_confidence: 0.94,
    needs_review: false,
    item_name: "Onion",
    item_canonical_id: "pyaaz",
    unit: "kg",
    reported_price: 160.0,
    official_price: 120.0,
    price_difference_pkr: 40.0,
    percentage_overcharge: 33.3,
    native_response: "شکایت پرائس مجسٹریٹ کو ارسال کر دی گئی ہے۔",
    routing_agency: "Rawalpindi DC Office",
    helpline_reference: "051-9292514",
    location_area: "Saddar, Rawalpindi",
    shop_name: "Kashmir Fruit & Veg",
    lat: 33.5962,
    lng: 73.0538,
    location_accuracy_m: 18,
    location_source: "GPS",
    admin_notes: null
  },
  {
    id: "comp-raw-003",
    created_at: "2026-10-09T16:05:00Z",
    transcript_raw: "ٹماٹر ڈھائی سو روپے کلو چارج کر رہے ہیں کمیٹی چوک پر۔",
    detected_language: "Urdu",
    category: "PERA - Overpricing",
    urgency: "High",
    status: "Investigating",
    extraction_confidence: 0.96,
    needs_review: false,
    item_name: "Tomato",
    item_canonical_id: "tamatar",
    unit: "kg",
    reported_price: 250.0,
    official_price: 150.0,
    price_difference_pkr: 100.0,
    percentage_overcharge: 66.7,
    native_response: "ٹماٹر کی قیمت میں شدید خلاف ورزی ہے۔ کارروائی شروع کر دی گئی ہے۔",
    routing_agency: "PERA - Price Enforcement",
    helpline_reference: "1717",
    location_area: "Committee Chowk, Rawalpindi",
    shop_name: "Madina Cash & Carry", // Repeat shop
    lat: 33.6094,
    lng: 73.0645,
    location_accuracy_m: 8,
    location_source: "GPS",
    admin_notes: "Repeat shop name detected. Priority check."
  },
  {
    id: "comp-isb-001",
    created_at: "2026-10-09T15:20:00Z",
    transcript_raw: "G-9 Markaz Bismillah store is charging 220 for Sugar instead of official 145.",
    detected_language: "English",
    category: "PERA - Overpricing",
    urgency: "High",
    status: "Pending",
    extraction_confidence: 0.97,
    needs_review: false,
    item_name: "Sugar",
    item_canonical_id: "cheeni",
    unit: "kg",
    reported_price: 220.0,
    official_price: 145.0,
    price_difference_pkr: 75.0,
    percentage_overcharge: 51.7,
    native_response: "Complaint received. Severe sugar overpricing reported. ICT Magistrate informed.",
    routing_agency: "ICT District Administration",
    helpline_reference: "051-9108194",
    location_area: "G-9 Markaz, Islamabad",
    shop_name: "Bismillah General Store",
    lat: 33.6891,
    lng: 73.0287,
    location_accuracy_m: 14,
    location_source: "GPS",
    admin_notes: null
  },
  {
    id: "comp-isb-002",
    created_at: "2026-10-09T14:10:00Z",
    transcript_raw: "F-10 Markaz shop selling broiler chicken meat at 650 per kg, list says 520.",
    detected_language: "English",
    category: "PERA - Overpricing",
    urgency: "Medium",
    status: "Pending",
    extraction_confidence: 0.95,
    needs_review: false,
    item_name: "Chicken Meat",
    item_canonical_id: "chicken_meat",
    unit: "kg",
    reported_price: 650.0,
    official_price: 520.0,
    price_difference_pkr: 130.0,
    percentage_overcharge: 25.0,
    native_response: "Complaint registered and routed to ICT Food & Price Magistrate.",
    routing_agency: "ICT District Administration",
    helpline_reference: "051-9108194",
    location_area: "F-10 Markaz, Islamabad",
    shop_name: "Al-Rehman Poultry",
    lat: 33.6938,
    lng: 73.0112,
    location_accuracy_m: 22,
    location_source: "GPS",
    admin_notes: null
  },
  {
    id: "comp-isb-003",
    created_at: "2026-10-09T13:45:00Z",
    transcript_raw: "آبپارہ مارکیٹ میں دال چنا 340 روپے کلو مانگ رہے ہیں جبکہ ریٹ لسٹ 280 ہے۔",
    detected_language: "Urdu",
    category: "PERA - Overpricing",
    urgency: "Medium",
    status: "Investigating",
    extraction_confidence: 0.93,
    needs_review: false,
    item_name: "Daal Chana",
    item_canonical_id: "daal_chana",
    unit: "kg",
    reported_price: 340.0,
    official_price: 280.0,
    price_difference_pkr: 60.0,
    percentage_overcharge: 21.4,
    native_response: "شکایت درج کر کے مجسٹریٹ کو منتقل کر دی گئی ہے۔",
    routing_agency: "ICT District Administration",
    helpline_reference: "051-9108194",
    location_area: "Aabpara, Islamabad",
    shop_name: "Mian Jee Kiryana",
    lat: 33.7081,
    lng: 73.0854,
    location_accuracy_m: 16,
    location_source: "GPS",
    admin_notes: "Notice served to shop owner."
  },
  {
    id: "comp-raw-004",
    created_at: "2026-10-09T12:30:00Z",
    transcript_raw: "Commercial Market Satellite Town: live chicken being sold for 420 per kg instead of official 345.",
    detected_language: "English",
    category: "PERA - Overpricing",
    urgency: "High",
    status: "Pending",
    extraction_confidence: 0.94,
    needs_review: false,
    item_name: "Chicken Live",
    item_canonical_id: "chicken_live",
    unit: "kg",
    reported_price: 420.0,
    official_price: 345.0,
    price_difference_pkr: 75.0,
    percentage_overcharge: 21.7,
    native_response: "Grievance queued for live market inspection team.",
    routing_agency: "PERA - Price Enforcement",
    helpline_reference: "1717",
    location_area: "Commercial Market, Rawalpindi",
    shop_name: "Punjab Broiler Mart",
    lat: 33.6375,
    lng: 73.0722,
    location_accuracy_m: 10,
    location_source: "GPS",
    admin_notes: null
  },
  {
    id: "comp-raw-005",
    created_at: "2026-10-09T11:15:00Z",
    transcript_raw: "Tench Bhata: Rotten vegetables mixed with fresh stock, charging 180 for onions.",
    detected_language: "English",
    category: "PFA - Food Safety",
    urgency: "High",
    status: "Resolved",
    extraction_confidence: 0.91,
    needs_review: false,
    item_name: "Onion",
    item_canonical_id: "pyaaz",
    unit: "kg",
    reported_price: 180.0,
    official_price: 120.0,
    price_difference_pkr: 60.0,
    percentage_overcharge: 50.0,
    native_response: "Forwarded to Punjab Food Authority for hygiene & price violation inspection.",
    routing_agency: "PFA - Punjab Food Authority",
    helpline_reference: "1223",
    location_area: "Tench Bhata, Rawalpindi",
    shop_name: "Bismillah General Store", // Repeat shop
    lat: 33.5821,
    lng: 73.0334,
    location_accuracy_m: 25,
    location_source: "GPS",
    admin_notes: "Fine of Rs 15,000 imposed by PFA safety inspector."
  },
  {
    id: "comp-isb-004",
    created_at: "2026-10-09T10:00:00Z",
    transcript_raw: "آئی ٹین سبزی منڈی میں لہسن 450 روپے کلو بیچ رہے ہیں جبکہ سرکاری لسٹ میں 320 ہے۔",
    detected_language: "Urdu",
    category: "PERA - Overpricing",
    urgency: "High",
    status: "Resolved",
    extraction_confidence: 0.96,
    needs_review: false,
    item_name: "Garlic",
    item_canonical_id: "lehsan",
    unit: "kg",
    reported_price: 450.0,
    official_price: 320.0,
    price_difference_pkr: 130.0,
    percentage_overcharge: 40.6,
    native_response: "آئی ٹین سبزی منڈی کے ہول سیل انسپکٹر کو شکایت بھیجی جا چکی ہے۔",
    routing_agency: "ICT Market Committee",
    helpline_reference: "051-9108194",
    location_area: "I-10 Sabzi Mandi, Islamabad",
    shop_name: "Khan Brothers Vegetable Depot",
    lat: 33.6492,
    lng: 73.0371,
    location_accuracy_m: 15,
    location_source: "GPS",
    admin_notes: "Market committee warned vendor. Official rate restored."
  },
  {
    id: "comp-isb-005",
    created_at: "2026-10-09T09:30:00Z",
    transcript_raw: "PWD Islamabad: Milk being sold at 230 per liter, official rate is 200.",
    detected_language: "English",
    category: "PERA - Overpricing",
    urgency: "Medium",
    status: "Pending",
    extraction_confidence: 0.95,
    needs_review: false,
    item_name: "Milk",
    item_canonical_id: "doodh",
    unit: "liter",
    reported_price: 230.0,
    official_price: 200.0,
    price_difference_pkr: 30.0,
    percentage_overcharge: 15.0,
    native_response: "Complaint logged for ICT rural price magistrate inspection.",
    routing_agency: "ICT District Administration",
    helpline_reference: "051-9108194",
    location_area: "PWD Islamabad",
    shop_name: "Madina Cash & Carry", // Repeat shop in PWD
    lat: 33.5852,
    lng: 73.1384,
    location_accuracy_m: 30,
    location_source: "GPS",
    admin_notes: null
  },
  {
    id: "comp-isb-006",
    created_at: "2026-10-09T08:45:00Z",
    transcript_raw: "بارہ کہو بازار میں روٹی 25 روپے کی دے رہے ہیں جبکہ سرکاری قیمت 16 روپے تندوری روٹی ہے۔",
    detected_language: "Urdu",
    category: "PERA - Overpricing",
    urgency: "High",
    status: "Investigating",
    extraction_confidence: 0.97,
    needs_review: false,
    item_name: "Roti",
    item_canonical_id: "roti",
    unit: "piece",
    reported_price: 25.0,
    official_price: 16.0,
    price_difference_pkr: 9.0,
    percentage_overcharge: 56.25,
    native_response: "نان بائیوں کے خلاف کارروائی کے لیے اسسٹنٹ کمشنر کو مطلع کر دیا گیا ہے۔",
    routing_agency: "ICT District Administration",
    helpline_reference: "051-9108194",
    location_area: "Barakahu, Islamabad",
    shop_name: "Al-Khair Tandoor",
    lat: 33.7423,
    lng: 73.1876,
    location_accuracy_m: 19,
    location_source: "GPS",
    admin_notes: "AC Secretariat directed special raid."
  },
  {
    id: "comp-raw-006",
    created_at: "2026-10-09T08:15:00Z",
    transcript_raw: "Saddar Rawalpindi: Beef boneless 1300 per kg vs 950 official.",
    detected_language: "English",
    category: "PERA - Overpricing",
    urgency: "High",
    status: "Pending",
    extraction_confidence: 0.92,
    needs_review: false,
    item_name: "Beef Boneless",
    item_canonical_id: "beef_boneless",
    unit: "kg",
    reported_price: 1300.0,
    official_price: 950.0,
    price_difference_pkr: 350.0,
    percentage_overcharge: 36.8,
    native_response: "Complaint recorded. Excessive meat overcharge flagged for Rawalpindi DC office.",
    routing_agency: "Rawalpindi DC Office",
    helpline_reference: "051-9292514",
    location_area: "Saddar, Rawalpindi",
    shop_name: "National Meat House",
    lat: 33.5985,
    lng: 73.0512,
    location_accuracy_m: 12,
    location_source: "GPS",
    admin_notes: null
  },
  // Complaints with Area Name Only (no exact GPS)
  {
    id: "comp-area-001",
    created_at: "2026-10-09T07:30:00Z",
    transcript_raw: "کراچی کمپنی میں لیموں 400 روپے کلو بیچ رہے ہیں، سرکاری ریٹ 250 ہے۔",
    detected_language: "Urdu",
    category: "PERA - Overpricing",
    urgency: "Medium",
    status: "Pending",
    extraction_confidence: 0.89,
    needs_review: false,
    item_name: "Lemon",
    item_canonical_id: "leemo",
    unit: "kg",
    reported_price: 400.0,
    official_price: 250.0,
    price_difference_pkr: 150.0,
    percentage_overcharge: 60.0,
    native_response: "شکایت موصول ہو چکی ہے۔ کراچی کمپنی مجسٹریٹ کو ارسال کر دی گئی ہے۔",
    routing_agency: "ICT District Administration",
    helpline_reference: "051-9108194",
    location_area: "Karachi Company",
    shop_name: "Subhan Fruit Corner",
    lat: 33.6910,
    lng: 73.0298,
    location_accuracy_m: null,
    location_source: "AreaName",
    admin_notes: "Approximate location via Area matching."
  },
  // Unlocated complaint
  {
    id: "comp-noloc-001",
    created_at: "2026-10-09T06:50:00Z",
    transcript_raw: "Cooking oil is 550 per liter everywhere, official price is 480.",
    detected_language: "English",
    category: "PERA - Overpricing",
    urgency: "Low",
    status: "Pending",
    extraction_confidence: 0.88,
    needs_review: true,
    item_name: "Cooking Oil",
    item_canonical_id: "cooking_oil",
    unit: "liter",
    reported_price: 550.0,
    official_price: 480.0,
    price_difference_pkr: 70.0,
    percentage_overcharge: 14.6,
    native_response: "Complaint recorded. Area not specified; marked for general monitoring.",
    routing_agency: "PERA - Price Enforcement",
    helpline_reference: "1717",
    location_area: null,
    shop_name: null,
    lat: null,
    lng: null,
    location_accuracy_m: null,
    location_source: "None",
    admin_notes: "No shop or area provided by citizen."
  }
];

export const MOCK_RATES = [
  { id: "aloo", name_en: "Potato (New)", name_ur: "آلو تازہ", price: 100.0, unit: "kg", category: "vegetable" },
  { id: "pyaaz", name_en: "Onion (Grade A)", name_ur: "پیاز اول", price: 120.0, unit: "kg", category: "vegetable" },
  { id: "tamatar", name_en: "Tomato", name_ur: "ٹماٹر", price: 150.0, unit: "kg", category: "vegetable" },
  { id: "cheeni", name_en: "Sugar (Refined)", name_ur: "چینی", price: 145.0, unit: "kg", category: "grocery" },
  { id: "chicken_live", name_en: "Chicken (Live)", name_ur: "زندہ برائلر مرغی", price: 345.0, unit: "kg", category: "meat" },
  { id: "chicken_meat", name_en: "Chicken Meat", name_ur: "مرغی کا گوشت", price: 520.0, unit: "kg", category: "meat" },
  { id: "doodh", name_en: "Fresh Milk", name_ur: "دودھ تازہ", price: 200.0, unit: "liter", category: "dairy" },
  { id: "dahi", name_en: "Yogurt", name_ur: "دہی", price: 220.0, unit: "kg", category: "dairy" },
  { id: "roti", name_en: "Tandoori Roti (100g)", name_ur: "تندوری روٹی", price: 16.0, unit: "piece", category: "grocery" },
  { id: "naan", name_en: "Khamiri Naan (120g)", name_ur: "خمیری نان", price: 25.0, unit: "piece", category: "grocery" },
  { id: "daal_chana", name_en: "Daal Chana", name_ur: "دال چنا", price: 280.0, unit: "kg", category: "pulses" },
  { id: "daal_masoor", name_en: "Daal Masoor", name_ur: "دال مسور", price: 310.0, unit: "kg", category: "pulses" },
  { id: "beef_boneless", name_en: "Beef Boneless", name_ur: "گائے کا گوشت بغیر ہڈی", price: 950.0, unit: "kg", category: "meat" },
  { id: "mutton", name_en: "Mutton", name_ur: "بکرے کا گوشت", price: 1900.0, unit: "kg", category: "meat" },
  { id: "lehsan", name_en: "Garlic (Local)", name_ur: "دیسی لہسن", price: 320.0, unit: "kg", category: "vegetable" },
  { id: "adrak", name_en: "Ginger (China)", name_ur: "ادرک", price: 480.0, unit: "kg", category: "vegetable" },
  { id: "cooking_oil", name_en: "Cooking Oil (Standard)", name_ur: "کوکنگ آئل", price: 480.0, unit: "liter", category: "grocery" },
  { id: "atta_10kg", name_en: "Wheat Flour 10kg Bag", name_ur: "گندم آٹا تھیلا 10 کلو", price: 1380.0, unit: "bag", category: "grocery" },
];

export const MOCK_ANALYTICS = {
  total_complaints: 142,
  overpricing_cases: 118,
  food_safety_cases: 16,
  infrastructure_cases: 8,
  average_overcharge_pct: 42.6,
  total_excess_charged_est_pkr: 384500.0,
  high_urgency_count: 53,
  needs_review_count: 11,
  most_gouged_items: [
    { item_name: "Potato", complaint_count: 42, average_overcharge_pct: 82.5, official_price: 100.0, highest_reported_price: 210.0 },
    { item_name: "Tomato", complaint_count: 36, average_overcharge_pct: 65.0, official_price: 150.0, highest_reported_price: 260.0 },
    { item_name: "Sugar", complaint_count: 28, average_overcharge_pct: 51.7, official_price: 145.0, highest_reported_price: 230.0 },
    { item_name: "Roti", complaint_count: 24, average_overcharge_pct: 56.3, official_price: 16.0, highest_reported_price: 25.0 },
    { item_name: "Chicken Meat", complaint_count: 19, average_overcharge_pct: 25.0, official_price: 520.0, highest_reported_price: 660.0 },
  ],
  hotspots: [
    { area: "Raja Bazaar, Rawalpindi", complaint_count: 38, avg_overcharge_pct: 68.4, top_violated_item: "Potato", dominant_category: "PERA - Overpricing", lat: 33.6028, lng: 73.0551 },
    { area: "G-9 Markaz, Islamabad", complaint_count: 27, avg_overcharge_pct: 52.1, top_violated_item: "Sugar", dominant_category: "PERA - Overpricing", lat: 33.6891, lng: 73.0287 },
    { area: "Commercial Market, Rawalpindi", complaint_count: 22, avg_overcharge_pct: 39.5, top_violated_item: "Chicken Meat", dominant_category: "PERA - Overpricing", lat: 33.6375, lng: 73.0722 },
    { area: "Saddar, Rawalpindi", complaint_count: 19, avg_overcharge_pct: 41.2, top_violated_item: "Beef Boneless", dominant_category: "PERA - Overpricing", lat: 33.5962, lng: 73.0538 },
    { area: "Aabpara, Islamabad", complaint_count: 16, avg_overcharge_pct: 35.8, top_violated_item: "Daal Chana", dominant_category: "PERA - Overpricing", lat: 33.7081, lng: 73.0854 },
  ],
  repeat_offenders: [
    {
      shop_name: "Madina Cash & Carry",
      area: "Raja Bazaar, Rawalpindi",
      violations_count: 9,
      items_gouged: ["Potato", "Tomato", "Milk"],
      max_overcharge_pct: 100.0,
      status: "Priority Enforcement",
      latest_complaint_date: "2026-10-09T18:40:00Z"
    },
    {
      shop_name: "Bismillah General Store",
      area: "G-9 Markaz, Islamabad",
      violations_count: 6,
      items_gouged: ["Sugar", "Onion"],
      max_overcharge_pct: 51.7,
      status: "Notice Issued",
      latest_complaint_date: "2026-10-09T15:20:00Z"
    },
    {
      shop_name: "Punjab Broiler Mart",
      area: "Commercial Market, Rawalpindi",
      violations_count: 4,
      items_gouged: ["Chicken Live", "Chicken Meat"],
      max_overcharge_pct: 25.0,
      status: "Pending Action",
      latest_complaint_date: "2026-10-09T12:30:00Z"
    }
  ]
};

